openapi: 3.0.3
info:
  title: Child Growth Assistant API
  description: An AI-powered parenting coach assistant that provides real-time advice on child development and parenting challenges.
  version: 1.0.0
  contact:
    name: Child Growth Assistant Support
    email: support@example.com
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
servers:
  - url: http://localhost:8011
    description: Local development server
  - url: https://api.childgrowthassistant.com
    description: Production server
paths:
  /healthz:
    get:
      tags:
        - Health
      summary: Health check endpoint
      description: Returns the health status of the service
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                required:
                  - status
        '500':
          description: Service is unhealthy
  /readyz:
    get:
      tags:
        - Health
      summary: Readiness check endpoint
      description: Returns the readiness status of the service
      responses:
        '200':
          description: Service is ready
          content:
            application/json:
              schema:
                type: object
                properties:
                  ready:
                    type: boolean
                    example: true
                required:
                  - ready
        '503':
          description: Service is not ready
  /api/coach/start:
    post:
      tags:
        - Coach
      summary: Start a new coaching session
      description: Initializes a new parenting coaching session with the provided parent information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartSessionRequest'
      responses:
        '200':
          description: Session started successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StartSessionResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
  /ws/coach/{session_id}:
    get:
      tags:
        - WebSocket
      summary: Coaching WebSocket endpoint
      description: Establishes a WebSocket connection for real-time coaching conversation
      parameters:
        - name: session_id
          in: path
          required: true
          description: The unique session identifier
          schema:
            type: string
      responses:
        '101':
          description: Switching to WebSocket protocol
          headers:
            Upgrade:
              schema:
                type: string
                example: websocket
            Connection:
              schema:
                type: string
                example: Upgrade
components:
  schemas:
    StartSessionRequest:
      type: object
      properties:
        parent_name:
          type: string
          description: The name of the parent starting the session
          example: "Sarah"
          minLength: 1
          maxLength: 100
      required:
        - parent_name
    StartSessionResponse:
      type: object
      properties:
        session_id:
          type: string
          description: Unique identifier for the coaching session
          example: "sess_a1b2c3d4e5f6"
        message:
          type: string
          description: Welcome message for the parent
          example: "Welcome Sarah! You can start chatting with your parenting coach."
      required:
        - session_id
        - message
    WebSocketMessage:
      type: object
      properties:
        type:
          type: string
          enum: [session_started, advice, text, noop]
          description: The type of message
        session_id:
          type: string
          description: Unique identifier for the coaching session
          example: "sess_a1b2c3d4e5f6"
        text:
          type: string
          description: The text content of the message
        timestamp:
          type: string
          format: date-time
          description: ISO 8601 timestamp of the message
      required:
        - type
        - timestamp
  responses:
    BadRequest:
      description: Bad request - invalid input
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
                example: "Request validation error"
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
tags:
  - name: Health
    description: Health and readiness check endpoints
  - name: Coach
    description: Coaching session endpoints
  - name: WebSocket
    description: Real-time coaching conversation endpoints