version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: lee_exercise10_frontend
    container_name: Lee_exercise10_frontend
    ports:
      - "8501:8501"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev:lan:https

