version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: exercise10_postgres
    environment:
      POSTGRES_DB: callcenter
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d callcenter"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: exercise10_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: exercise10_backend
    ports:
      - "8600:8600"
    environment:
      DATABASE_URL: postgresql+asyncpg://admin:password@postgres:5432/callcenter
      REDIS_URL: redis://redis:6379
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SECRET_KEY: ${SECRET_KEY:-your-secret-key}
      CORS_ORIGINS: '["http://localhost:8501","http://localhost:3001"]'
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8600 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: exercise10_frontend
    ports:
      - "8501:8501"
    env_file:
      - ./frontend/.env.local
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    command: npm run dev

volumes:
  postgres_data:

